# Site settings
title: Aurora Borealis
tagline: "The Northern Lights"
# email: your-email@domain.com
description: "The Northern Lights"
baseurl: ""
url: "http://za.github.io"

# Build settings
markdown: kramdown
permalink: pretty
